version: '3'
services:
  hello-service:
    restart: always
    build: ./helloService
    links:
      - hello-mongo

  welcome-service:
    restart: always
    build: ./welcomeService
    links:
      - welcome-mongo

  load-balancer:
    build: ./nginx
    ports:
      - '80:80'
    links:
      - hello-service
      - welcome-service

  hello-mongo:
    image: mongo
    container_name: hello-mongo
    command: mongod --port 27018

  welcome-mongo:
    image: mongo
    container_name: welcome-mongo