version: '2'
services:
  hello-service:
    restart: always
    build: ./helloService
    links:
      - hello-mongo
    networks:
      - db
      - web
  load-balancer:
    build: ./nginx
    ports:
      - '80:80'
    links:
      - hello-service
      - welcome-service
    networks:
      - web
  hello-mongo:
    image: mongo
    container_name: hello-mongo
    command: mongod --port 27018
    ports:
      - '27018:27018'
    networks:
      - db

networks:
  db:
    driver: bridge
  lb:
    driver: bridge