version: '2'
services:
  hello-service:
    restart: always
    build: iturie26/hello:001
    scale: 4
    links:
      - hello-mongo

  load-balancer:
    build: ./nginx
    ports:
      - '80:80'
    links:
      - hello-service
      - welcome-service

  hello-mongo:
    image: mongo
    container_name: hello-mongo
    command: mongod --port 27018
    ports:
      - '27018:27018'
