version: '3'
services:
  gateway:
    container_name: gateway-node
    restart: always
    build: ./gateway
    ports:
      - '3333:3333'
    links:
      - hello-service
      - welcome-service

  hello-service:
    container_name: hello-service
    restart: always
    build: ./helloService
    ports:
      - '2222:2222'
    links:
      - hello-service-mongo

  welcome-service:
    container_name: welcome-service
    restart: always
    build: ./welcomeService
    ports:
      - '1111:1111'
    links:
      - welcome-service-mongo

  hello-mongo:
    image: mongo
    container_name: hello-service-mongo
    ports:
      - '27017:27017'

  welcome-mongo:
    image: mongo
    container_name: welcome-service-mongo
    ports:
      - '27018:27017'