version: '3'
services:
  hello-service:
    image: ituriel26/hello:001
    restart: always
    links:
      - hello-mongo

  welcome-service:
    restart: always
    image: ituriel26/welcome:001
    links:
      - welcome-mongo

  load-balancer:
    image: ituriel26/nginx:001
    ports:
      - '80:80'
    links:
      - hello-service
      - welcome-service

  hello-mongo:
    image: mongo
    container_name: hello-mongo
    command: mongod --port 27018
    ports:
      - '27018:27018'

  welcome-mongo:
    image: mongo
    container_name: welcome-mongo
    ports:
      - '27017:27017'