version: '3'
services:
#  gateway:
#    restart: always
#    build: ./gateway
#    links:
#      - load-balancer-welcome
#      - load-balancer-hello

  hello-service:
    restart: always
    build: ./helloService
    links:
      - hello-mongo

  welcome-service:
    restart: always
    build: ./welcomeService
    links:
      - welcome-mongo

  load-balancer-hello:
    build: nginx/hello
    ports:
      - '8022:80'
    links:
      - hello-service
  load-balancer-welcome:
    build: nginx/welcome
    ports:
      - '8011:80'
    links:
      - welcome-service

  hello-mongo:
    image: mongo
    container_name: hello-mongo
    command: mongod --port 27018
    ports:
      - '27018:27018'

  welcome-mongo:
    image: mongo
    container_name: welcome-mongo
    ports:
      - '27017:27017'