version: '3'
services:
  hello-service:
    restart: always
    build: ./helloService
    links:
      - hello-mongo
    networks:
      - db
      - lb

  welcome-service:
    restart: always
    build: ./welcomeService
    links:
      - hello-mongo
    networks:
      - db
      - lb

  load-balancer:
    build: ./nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
    links:
      - hello-service
      - welcome-service
    networks:
      - lb

  hello-mongo:
    image: mongo
    container_name: hello-mongo
    command: mongod --port 27018
    ports:
      - '27018:27018'
    networks:
      - db
  welcome-mongo:
    image: mongo
    container_name: hello-mongo
    ports:
      - '27017:27017'
    networks:
      - db
networks:
  db:
    driver: bridge
  lb:
    driver: bridge